appVersion: v1

Dep:
  namespace: default
  label: helm-ms
  replicaCount: 1
  image:
    repo: jeba4all/applogin_demo
    tag:  1
  resources:
    requests:
      cpu: 250m
    limits:
      cpu: 500m
  container_port: 8080
Svc:
  namespace: default
  label: helm-ms
  port: 80
  target_port: 8080
